# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 00:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('name', models.CharField(error_messages={'unique': 'El nombre de usuario ya existe'}, max_length=255, unique=True, verbose_name='name')),
                ('phone_Number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="El numero tiene que tener este formato '55-5555-5555'.", regex='^\\+?1?\\d{10,15}$')], verbose_name='phone number')),
                ('lat', models.CharField(max_length=500, verbose_name='lat')),
                ('long', models.CharField(max_length=500, verbose_name='long')),
                ('type', models.CharField(choices=[('C', 'Comida'), ('ET', 'Electronica y Tecnologia'), ('RA', 'Ropa y Accesorios'), ('M', 'Musica'), ('E', 'Entretenimiento'), ('O', 'Otros')], max_length=255, verbose_name='type')),
                ('opening', models.TimeField(verbose_name='opening')),
                ('closing', models.TimeField(verbose_name='closing')),
            ],
        ),
    ]
